site_name: ccss17
site_author: ccsss
# repo_name: ccss17.github.io
# repo_url: https://github.com/ccss17/ccss17.github.io

nav:
  - Home: index.md
  # - 화가의 일기(소설):
  #   - intro: diary/intro.md
  #   - 19xx.7.23 용서란 무엇인가 : diary/19xx.7.23.md
  #   - 19xx.7.29 제목 없음 : diary/19xx.7.29.md
  #   - 19xx.8.2 내 마음이 죽은 것 같다 : diary/19xx.8.2.md
  #   - 19xx.8.13-1 내 힘으로 살 수 없는 것 : diary/19xx.8.13-1.md
  #   - 19xx.8.13-2 세상을 어떻게 바꿀 수 있을까? : diary/19xx.8.13-2.md
  #   - 19xx.8.17 소설 1 : diary/19xx.8.17.md
  #   - 19xx.9.1 그들은, 그들은 그냥 죽은 것이다: diary/19xx.9.1.md
  #   - 19xx.9.6 아이에게 : diary/19xx.9.6.md
  #   - 19xx.10.11 죽을 수 없다 : diary/19xx.10.11.md
  #   - 19xx.10.14-1 푸르고 텅 빈 곳 : diary/19xx.10.14-1.mdj
  #   - 19xx.10.14-2 외로움 : diary/19xx.10.14-2.md
  #   - 19xx.10.16 열등감 : diary/19xx.10.16.md
  #   - 19xx.10.17 무제 : diary/19xx.10.17.md
  #   - 19xx.10.23 현실 : diary/19xx.10.23.md
  #   - 19xx.10.25 내 일기를 돌아봤다 : diary/19xx.10.25.md
  #   - 19xx.11.10 혼잣말: diary/19xx.11.10.md
  #   - 19xx.11.13 춥다: diary/19xx.11.13.md
  # - HAI:
  #   - 1. 기초: HAI/base.md
  #   - 2. 생각: HAI/think.md
  #   - 3. 실행: HAI/doit.md
  #   - 수학의 역사: HAI/math_history.md
  #   - 4. 수학역사 1차 추상화: HAI/abstract_math_history.md
  #   - 컴퓨터역사(괴델의 불완전성 정리): HAI/5.md
  #   - 컴퓨터역사2(튜링의 불완전성 증명): HAI/6.md
  #   - 컴퓨터역사3(튜링기계의 구현): HAI/7.md
  #   - 컴퓨터역사4(소프트웨어와 알고리즘): HAI/8.md
  #   - 컴퓨터역사5(초지능): HAI/9.md
  # - 재료:
  - AI: 
    - DL from stratch 메모: AI/dl_from_scratch.md
    - DL from stratch 메모2: AI/dl_from_scratch2.md
    - DL from stratch 메모3: AI/dl_from_scratch3.md
    - DL from stratch 메모4: AI/dl_from_scratch4.md
    - 인공지능 메모3: AI/ai.md
  - 정보이론: Philosophy/information.md
  - Computer: 
    - Makefile: Computer/makefile.md
    - Git: Computer/git.md
    - Docker: Computer/docker.md
    - CUDA: Computer/cuda.md
  - Philosophy: 
    - 철학 메모: Philosophy/philosophy.md
    - 정신지도규칙/방법서설 메모(데카르트): Philosophy/descartes.md
  - Tex 수학기호: tex.md
  - Paper:
    - Facenet (2015): paper/facenet.md
    - Quadruplet (2017): paper/quadruplet.md
  - Math: 
    - 수학기초론: 
      - 논리학: Math/Foundations/logic.md
      - 집합론: Math/Foundations/math.md
      - 수리논리학: Math/Foundations/mathmatical_logic.md
    - 산술/대수학: 
      - 기초 산술: Math/Algebra/arithmetic.md
      - 추상대수학: Math/Algebra/abstract_algebra.md
      - 대수학: Math/Algebra/algebra.md
    - 해석학: 
      - 해석학: Math/Analysis/anal.md
      - 삼각함수: Math/Analysis/trig.md
      - 함수: Math/Analysis/function.md
    - 확률: 
      - 조합: Math/Probability/comb.md
      - 확률: Math/Probability/prob.md
    - 통계학: 
      - 도수분포의 평균,분산,표준편차: Math/Statistics/stat.md
      - 이산확률변수의 평균,분산,표준편차: Math/Statistics/stat2.md
      - 이항분포의 평균,분산,표준편차: Math/Statistics/stat3.md
      - 연속확률변수의 평균,분산,표준편차: Math/Statistics/stat4.md
      - 통계적 추정: Math/Statistics/stat5.md
      - 상관관계 분석: Math/Statistics/stat6.md
    - 미적분: 
      - 극한: Math/Calculus/cal.md
      - 미분: Math/Calculus/cal2.md
      - 적분: Math/Calculus/cal3.md
      - 미분2: Math/Calculus/cal4.md
      - 적분2: Math/Calculus/cal5.md
      - 벡터해석학: Math/Calculus/vector.md
      - 미적분: Math/Calculus/cal6.md
      - 다변수함수의 미분의 일반적 정의: Math/Calculus/cal7.md
      - 텐서해석학: Math/Calculus/cal8.md
    - 선형대수학: 
      - 선형방정식: Math/LinearAlgebra/la.md
      - 행렬대수: Math/LinearAlgebra/la2.md
      - 행렬식: Math/LinearAlgebra/la3.md
      - 벡터공간: Math/LinearAlgebra/la4.md
      - 고유벡터: Math/LinearAlgebra/la5.md
      - 직교: Math/LinearAlgebra/la6.md
    - 다중선형대수학: 
      - (임시): Math/MultiLinearAlgebra/mla.md
    - 위상수학: 
      - (임시): Math/Topology/topology.md
  - ProgrammerBase: 
    - ProgrammerBase: ProgrammerBase/readme.md
    - Contents:
      - Day 1: ProgrammerBase/01-Day1/readme.md
      - Day 2: ProgrammerBase/02-Day2/readme.md
      - Day 3: ProgrammerBase/03-Day3/readme.md
      - Day 4: ProgrammerBase/04-Day4/readme.md
      - Day 5: ProgrammerBase/05-Day5/readme.md
    - Docker: ProgrammerBase/docker.md
    - Information: ProgrammerBase/information.md
    - Git: ProgrammerBase/git.md
    - VSCode: ProgrammerBase/vscode.md
    - Markdown: ProgrammerBase/markdown.md
    - Tmux: ProgrammerBase/tmux.md
    - Vim: ProgrammerBase/vim.md
    - CLI: ProgrammerBase/cli.md
    - 수학의 역사: ProgrammerBase/math.md
    - 불완전성 정리: ProgrammerBase/godel.md
    - 튜링의 증명: ProgrammerBase/turing.md
    - 기술적 특이점: ProgrammerBase/future.md
  - 강의메모:
    - 딥러닝 응용: lecture/20-2/dl.md
    - 컴퓨터과학적 사고: lecture/20-2/cthink.md
    - Programming Language: lecture/20-2/pl.md
    - Korean History: lecture/20-2/koreahistory.md
    - Calculus 2: lecture/20-2/cal2.md
  - Algorithm:
    - 시간복잡도: Algorithm/timecomplexity.md
    - Leetcode: Algorithm/leetcode.md

theme: 
  name: material
  palette:
    # primary: black
    primary: white
    scheme: default
  font:
    text: Nanum Gothic
  language: kr
  logo: assets/images/favicon.png
  favicon: assets/images/favicon.ico

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/highlight.min.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.js
  - javascripts/config.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.11.1/katex.min.css
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/styles/github-gist.min.css
  - stylesheets/config.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ccss17

markdown_extensions:
  - toc:
      permalink: "&para;"
      baselevel: 2
      toc_depth: 2-4
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - attr_list
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink
  - pymdownx.tasklist:
      clickable_checkbox: false
      custom_checkbox: true
