name: ci
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material ghp-import
      - run: mkdocs build
      - run: python config.py
      - run: ghp-import site
      - run: git push -f origin gh-pages
      # - run: mkdocs gh-deploy --force